language: go
go:
    - 1.6
    - 1.7
    - 1.8

before_install:
    - go get -u github.com/alecthomas/gometalinter
    - gometalinter --install --update

script:
    - go get -u -v
    - go build
    - gometalinter -D gas -D errcheck -e 'should have comment' ./...

